module.exports = {
  ERROR: 'ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  PROPERTY_INVALID: 'PROPERTY_INVALID',
  TOKEN_NOT_PROVIDED: 'TOKEN_NOT_PROVIDED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  NOT_FOUND: 'NOT_FOUND',
  LIMIT_API_CALL: 'LIMIT_API_CALL',
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
};
